version: '3.4'

services:
  covid-angular-dotnetcore:
    image: covid-angular-dotnetcore
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3000
      - 5005:5005